version: "3"

volumes:
  upload:
  sqlite:

services:
  redis:
    image: redis:latest
    expose:
      - "6379"
  backend:
    build:
      context: ./docker/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - upload:/usr/src/app/upload
      - sqlite:/usr/src/app/sqlite
    depends_on:
      - redis
    entrypoint: ./run.sh
  celery:
    build:
      context: ./docker/backend
    depends_on:
      - redis
      - backend
    links:
      - redis:redis
    env_file:
      - .env
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - upload:/usr/src/app/upload
    command: celery -A backend.celery_app worker --loglevel=info

